-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    A13: in std_logic;
    A14: in std_logic;
    A15: in std_logic;
    PHI2: in std_logic;
    notRW: in std_logic;
    A12: in std_logic;
    A18: in std_logic;
    A17: in std_logic;
    notWERAM: out std_logic;
    notCSRAM: out std_logic;
    MBA15: out std_logic;
    notCSROM: out std_logic;
    RW: out std_logic);
end main;

architecture Behavioral of main is
  signal RW_temp: std_logic;
  signal notCSRAM_temp: std_logic;
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
begin
  s0 <= (A12 AND A13 AND NOT A14 AND A15);
  s1 <= (NOT A12 AND A13 AND NOT A14 AND A15);
  s2 <= (A12 AND NOT A13 AND NOT A14 AND A15);
  s3 <= (NOT A12 AND NOT A13 AND NOT A14 AND A15);
  s4 <= (A12 AND A13 AND A14 AND NOT A15);
  s5 <= (NOT A12 AND A13 AND A14 AND NOT A15);
  MBA15 <= (A13 OR A14 OR A15);
  RW_temp <= NOT notRW;
  s6 <= (A12 AND NOT A13 AND A14 AND NOT A15);
  s7 <= (NOT A12 AND NOT A13 AND A14 AND NOT A15);
  s8 <= (s7 OR s6 OR s5 OR s4 OR s3 OR s2);
  notCSRAM_temp <= NOT ((s8 AND NOT A17 AND NOT A18) OR (s8 AND A17 AND NOT A18) OR ((s7 OR s6 OR s5 OR s4) AND NOT A17 AND A18) OR (A17 AND A18 AND (s1 OR s0)));
  notCSROM <= NOT (((s1 OR s0 OR (NOT A12 AND NOT A13 AND A14 AND A15) OR (A12 AND NOT A13 AND A14 AND A15) OR (NOT A12 AND A13 AND A14 AND A15) OR (A12 AND A13 AND A14 AND A15)) AND NOT A17 AND NOT A18) OR ((s1 OR s0 OR (NOT A12 AND NOT A13 AND A14 AND A15) OR (A12 AND NOT A13 AND A14 AND A15) OR (NOT A12 AND A13 AND A14 AND A15) OR (A12 AND A13 AND A14 AND A15)) AND A17 AND NOT A18) OR (A18 AND NOT A17 AND (s3 OR s2 OR s1 OR s0 OR (NOT A12 AND NOT A13 AND A14 AND A15) OR (A12 AND NOT A13 AND A14 AND A15) OR (NOT A12 AND A13 AND A14 AND A15) OR (A12 AND A13 AND A14 AND A15))) OR (A17 AND A18 AND s8) OR (A17 AND A18 AND ((NOT A12 AND NOT A13 AND A14 AND A15) OR (A12 AND NOT A13 AND A14 AND A15) OR (NOT A12 AND A13 AND A14 AND A15) OR (A12 AND A13 AND A14 AND A15))));
  notWERAM <= NOT (PHI2 AND RW_temp AND NOT notCSRAM_temp);
  notCSRAM <= notCSRAM_temp;
  RW <= RW_temp;
end Behavioral;
