/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module ATF16V8_Logic_V2_2c (
  input A13,
  input A14,
  input A15,
  input PHI2,
  input \/RW ,
  input A12,
  input A18,
  input A17,
  output \/WERAM ,
  output \/CSRAM ,
  output MBA15,
  output \/CSROM ,
  output RW
);
  wire RW_temp;
  wire \/CSRAM_temp ;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  assign s0 = (A12 & A13 & ~ A14 & A15);
  assign s1 = (~ A12 & A13 & ~ A14 & A15);
  assign s2 = (A12 & ~ A13 & ~ A14 & A15);
  assign s3 = (~ A12 & ~ A13 & ~ A14 & A15);
  assign s4 = (A12 & A13 & A14 & ~ A15);
  assign s5 = (~ A12 & A13 & A14 & ~ A15);
  assign MBA15 = (A13 | A14 | A15);
  assign RW_temp = ~ \/RW ;
  assign s6 = (A12 & ~ A13 & A14 & ~ A15);
  assign s7 = (~ A12 & ~ A13 & A14 & ~ A15);
  assign s8 = (s7 | s6 | s5 | s4 | s3 | s2);
  assign \/CSRAM_temp  = ~ ((s8 & ~ A17 & ~ A18) | (s8 & A17 & ~ A18) | ((s7 | s6 | s5 | s4) & ~ A17 & A18) | (A17 & A18 & (s1 | s0)));
  assign \/CSROM  = ~ (((s1 | s0 | (~ A12 & ~ A13 & A14 & A15) | (A12 & ~ A13 & A14 & A15) | (~ A12 & A13 & A14 & A15) | (A12 & A13 & A14 & A15)) & ~ A17 & ~ A18) | ((s1 | s0 | (~ A12 & ~ A13 & A14 & A15) | (A12 & ~ A13 & A14 & A15) | (~ A12 & A13 & A14 & A15) | (A12 & A13 & A14 & A15)) & A17 & ~ A18) | (A18 & ~ A17 & (s3 | s2 | s1 | s0 | (~ A12 & ~ A13 & A14 & A15) | (A12 & ~ A13 & A14 & A15) | (~ A12 & A13 & A14 & A15) | (A12 & A13 & A14 & A15))) | (A17 & A18 & s8) | (A17 & A18 & ((~ A12 & ~ A13 & A14 & A15) | (A12 & ~ A13 & A14 & A15) | (~ A12 & A13 & A14 & A15) | (A12 & A13 & A14 & A15))));
  assign \/WERAM  = ~ (PHI2 & RW_temp & ~ \/CSRAM_temp );
  assign \/CSRAM  = \/CSRAM_temp ;
  assign RW = RW_temp;
endmodule
